# 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operation??

Ans:

Purpose of NumPy:

(1) Efficient Array and Matrix Operations: NumPy is primarily used for creating and manipulating arrays (n-dimensional, homogeneous data structures) and matrices, which are fundamental to many scientific and engineering calculations.

(2) Foundation for Other Libraries: NumPy serves as the foundation for many other libraries used in data science and scientific computing, such as SciPy, Pandas, TensorFlow, and Scikit-learn. These libraries rely on NumPy arrays for data storage and manipulation.

(3) Numerical Computation: NumPy provides a comprehensive suite of mathematical functions, including linear algebra, random number generation, Fourier transforms, and more, which are essential for performing complex numerical computations.

Advantages of NumPy:

Performance:

Speed: NumPy arrays are more efficient in terms of memory and performance compared to Python’s built-in lists. This is because NumPy arrays are implemented in C and optimized for fast computation.
Vectorization: NumPy allows for vectorized operations, which means operations are applied directly on entire arrays rather than element by element. This significantly speeds up computations.

Memory Efficiency:

NumPy arrays are stored in contiguous blocks of memory, which allows for efficient memory use and faster access compared to Python lists that store references to objects.

Broad Functionality:

Mathematical Operations: NumPy provides a wide range of functions for performing element-wise operations, aggregations, reshaping, slicing, and more. This makes it easy to manipulate large datasets without the need for loops.
Linear Algebra: NumPy includes extensive support for linear algebra, including matrix multiplication, eigenvalues, and singular value decomposition (SVD).
Random Sampling: It includes tools for generating random numbers and sampling, which are essential in simulations and probabilistic models.
Integration with Other Tools:

NumPy arrays can easily integrate with other data processing tools and libraries. For example, Pandas uses NumPy under the hood for its DataFrame objects, and Matplotlib uses NumPy for plotting and visualization.

How NumPy Enhances Python’s Capabilities:

Scalability: With NumPy, Python can handle large datasets and perform operations on multi-dimensional data efficiently, making it scalable for big data tasks.

Enhanced Mathematical Computations: NumPy’s array and matrix operations are optimized for speed and efficiency, making Python suitable for high-performance computing tasks, which are common in scientific research and data analysis.

Improved Precision and Control: NumPy allows for the use of specific data types (like float32, int64, etc.), providing greater control over numerical precision, which is crucial in scientific calculations.


# 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

Ans:
np.mean():

Purpose: Calculates the arithmetic mean (average) of the elements in an array.
Parameters:
axis (optional): Specifies the axis along which to compute the mean. If not specified, it calculates the mean of all the elements in the array.
dtype (optional): Specifies the data type to use for the calculation.
out (optional): Allows you to store the result in a specified array instead of creating a new one.
Behavior: It treats all elements in the input array equally, meaning it calculates a simple arithmetic mean without considering any weights.
Use Case: Use np.mean() when you want to calculate a simple average of the values in an array, where each element contributes equally to the final mean.

example:
import numpy as np

arr = np.array([1, 2, 3, 4])

mean_value = np.mean(arr)

print(mean_value)  # Output: 2.5

np.average():

Purpose: Computes the weighted average of the elements in an array. It can also compute the simple average if weights are not provided.
Parameters:
weights (optional): An array of the same shape as the input array that specifies the weight for each element. The weighted average is computed as the sum of the product of the elements and their corresponding weights, divided by the sum of the weights.
axis (optional): Specifies the axis along which to compute the average.
returned (optional): If True, the function returns a tuple containing the calculated average and the sum of the weights.
Behavior: When weights are provided, np.average() computes a weighted average where elements with higher weights contribute more to the final average.
Use Case: Use np.average() when you need to calculate an average that takes into account different weights for the elements, such as when some data points are more significant than others.

example:
import numpy as np

arr = np.array([1, 2, 3, 4])

weights = np.array([1, 2, 1, 2])

weighted_average = np.average(arr, weights=weights)

print(weighted_average)  # Output: 2.8333333333333335



#  Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays?
ans:
Reversing a 1D Array:
1. Using Slicing
You can reverse a 1D array by using Python's slicing notation with a step of -1
example:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

reversed_arr = arr[::-1]

print(reversed_arr)  # Output: [5 4 3 2 1]

2. Using np.flip()
The np.flip() function reverses the order of elements in an array along the specified axis
example:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

reversed_arr = np.flip(arr)

print(reversed_arr)  # Output: [5 4 3 2 1]

Reversing a 2D Array
1. Using Slicing
You can reverse rows, columns, or both by applying slicing with -1 to the respective axes.
example:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = arr[::-1, :]
print(reversed_rows)
Output:
[[7 8 9]
 [4 5 6]
[1 2 3]]

2. Using np.flip()
np.flip() can be used to reverse the array along a specific axis.

example:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = np.flip(arr, axis=0)
print(reversed_rows)
 Output:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]




# 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

Ans:
Determining the Data Type of Elements in a NumPy Array
In NumPy, you can determine the data type of the elements in an array using the dtype attribute. This attribute returns an object that describes the type of the elements stored in the array.
Example:
import numpy as np

arr = np.array([1, 2, 3])

print(arr.dtype)  # Output: int64 (or int32, depending on the system)

arr_float = np.array([1.0, 2.0, 3.0])

print(arr_float.dtype)  # Output: float64

1. Memory Management:
Memory Allocation: The data type of a NumPy array determines how much memory each element occupies. For example, an int32 array (32-bit integer) will use 4 bytes per element, whereas an int64 array (64-bit integer) will use 8 bytes per element. Choosing the appropriate data type can save significant amounts of memory, especially for large arrays.

Example: An array of one million integers stored as int32 will use 4 MB of memory, while the same array stored as int64 will use 8 MB.
Precision and Storage Trade-off: Different data types offer different levels of precision. For instance, float32 has less precision than float64, but it uses half the memory. Depending on the application's requirements, you may choose a data type that balances precision with memory usage.

Example: For storing sensor data that doesn't require high precision, using float32 might be sufficient and more memory-efficient than float64.
2. Performance Optimization:
Computation Speed: Smaller data types typically lead to faster computations because less data needs to be processed and moved around in memory. For example, operations on int32 arrays are generally faster than those on int64 arrays, simply because the smaller data type is quicker to handle in memory.

Cache Efficiency: The choice of data type can affect how well data fits into the CPU cache, which is a small, fast memory used to store frequently accessed data. Smaller data types allow more elements to be stored in the cache, leading to faster access and improved performance.

Vectorization: NumPy operations are highly optimized for vectorized operations, where entire arrays are processed at once instead of element by element. Using appropriate data types can further enhance the efficiency of these operations.

3. Compatibility and Interoperability:
Interfacing with Other Systems: When interfacing with external libraries or systems (e.g., file formats, databases), the data type might need to match the expected format. Choosing the correct data type ensures that data can be correctly interpreted by other systems.

Avoiding Overflows and Underflows: Using an inappropriate data type might result in overflows (when a value exceeds the maximum limit of the data type) or underflows (when a value is too small for the data type). Selecting a data type that comfortably accommodates the expected range of values is important for the accuracy and reliability of computations.



# Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
Ans:
What are ndarrays in NumPy?
ndarray (short for "N-dimensional array") is the core data structure in NumPy. It represents a multi-dimensional, homogeneous array of fixed-size items. The elements in an ndarray are all of the same data type, and this homogeneity is one of the factors that make ndarrays more efficient and faster than Python lists for numerical operations.

Key Features of ndarrays:
Homogeneous Data:

All elements in an ndarray have the same data type (dtype). This uniformity allows for efficient memory management and fast computation.
N-Dimensional:

An ndarray can be multi-dimensional (1D, 2D, 3D, etc.), making it suitable for representing vectors, matrices, and tensors. The dimensionality is defined by the shape attribute, which is a tuple representing the size of the array along each dimension.
Efficient Memory Layout:

ndarrays are stored in contiguous blocks of memory, allowing for fast access and efficient operations. This layout contrasts with Python lists, which are arrays of pointers to objects and can be spread across different memory locations.
Broadcasting:

NumPy supports broadcasting, a powerful mechanism that allows ndarray operations to work on arrays of different shapes in a way that makes sense (e.g., adding a scalar to every element of an array).
Vectorized Operations:

Operations on ndarrays are vectorized, meaning they can be applied to entire arrays at once without the need for explicit loops. This approach is much faster than iterating over elements manually.

Differences Between ndarrays and Standard Python Lists:
Homogeneity:

ndarray: All elements must be of the same data type, ensuring uniformity.
Python List: Can contain elements of different data types (e.g., integers, strings, floats).
Memory Efficiency:

ndarray: Uses a contiguous block of memory for all elements, which is more memory-efficient.
Python List: Each element is a reference to an object in memory, leading to overhead and less efficient memory usage.
Performance:

ndarray: Operations are vectorized and performed in C, making them significantly faster for large-scale numerical computations.
Python List: Operations are performed element by element in Python, which is slower, especially for large datasets.
Multi-Dimensional Capabilities:

ndarray: Supports multi-dimensional arrays, making it suitable for representing complex data structures like matrices and tensors.
Python List: Lists can be nested to create multi-dimensional structures, but they are not as efficient or intuitive as ndarrays.
Broadcasting:

ndarray: Supports broadcasting, allowing operations between arrays of different shapes.
Python List: Does not support broadcasting; manual loops are required to achieve similar functionality.

# 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
Ans:
NumPy arrays (ndarrays) offer significant performance benefits over Python lists for large-scale numerical operations. These advantages stem from NumPy's design, which emphasizes efficiency, speed, and ease of use in scientific computing and data analysis. Here's an analysis of the key performance benefits:

1. Memory Efficiency
Contiguous Memory Layout:

NumPy Arrays: ndarrays are stored in a contiguous block of memory, which means all elements are stored next to each other in memory. This layout allows for faster access and efficient use of cache memory.
Python Lists: Lists are arrays of pointers to objects, meaning each element is a reference to an object stored elsewhere in memory. This indirection results in more memory overhead and less efficient memory access.
Fixed Data Types:

NumPy Arrays: All elements in a NumPy array have the same data type (dtype), which allows for uniform memory allocation and reduces overhead. For instance, a float32 array uses 4 bytes per element, while a float64 array uses 8 bytes per element.
Python Lists: Lists can contain elements of different data types, each requiring its own memory allocation, which can lead to inefficient use of memory.

2. Speed and Performance
Vectorized Operations:
NumPy Arrays: NumPy supports vectorized operations, which means operations can be applied to entire arrays without the need for explicit loops. These operations are implemented in highly optimized C code, making them much faster than equivalent operations using Python loops.
Python Lists: Operations on lists typically require explicit loops, where each element is processed one at a time. Python's loops are interpreted, which is significantly slower than NumPy's compiled code.
examples:
import numpy as np

NumPy Array

arr_np = np.array([1, 2, 3, 4, 5])

arr_np_squared = arr_np ** 2  # Vectorized operation

print(arr_np_squared)  # Output: [ 1  4  9 16 25]

 Python List:
 
arr_list = [1, 2, 3, 4, 5]

arr_list_squared = [x ** 2 for x in arr_list]  # Looping operation

print(arr_list_squared)  # Output: [1, 4, 9, 16, 25]

 Efficient Broadcasting:
 
Broadcasting:
NumPy Arrays: Broadcasting allows NumPy to perform operations on arrays of different shapes without needing to manually resize or replicate data. This feature reduces the need for unnecessary memory allocation and computation.
Python Lists: Python lists do not support broadcasting, so operations on lists of different sizes require explicit looping or manual data replication.

example:
import numpy as np

 Broadcasting in NumPy
 
arr_np = np.array([1, 2, 3])

arr_broadcast = arr_np + 5  # Adds 5 to each element

print(arr_broadcast)  # Output: [6 7 8]

4. Advanced Mathematical Functions
Comprehensive Function Library:
NumPy Arrays: NumPy provides a wide range of mathematical, statistical, and linear algebra functions that are optimized for performance. These functions operate directly on ndarrays, ensuring fast and accurate computations.
Python Lists: While Python has basic math functions, complex operations often require external libraries or custom code, which can be slower and more cumbersome to implement.



# 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output?
Ans:
In NumPy, the vstack() and hstack() functions are used to stack arrays vertically and horizontally, respectively. These functions allow you to combine multiple arrays into a single array in different ways, depending on the desired orientation. Here's a comparison and examples of how to use them:

vstack() Function
Purpose: The vstack() function is used to stack arrays vertically (row-wise). It concatenates the input arrays along the first axis (axis 0).
Input Requirement: The input arrays must have the same number of columns (i.e., the same shape along the second axis, axis 1).
example:
import numpy as np

Creating two 1D arrays

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

 Using vstack to stack them vertically
 
result_vstack = np.vstack((arr1, arr2))

print(result_vstack)

hstack() Function:
Purpose: The hstack() function is used to stack arrays horizontally (column-wise). It concatenates the input arrays along the second axis (axis 1).
Input Requirement: The input arrays must have the same number of rows (i.e., the same shape along the first axis, axis 0).
example:
import numpy as np

 Creating two 1D arrays
 
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

 Using hstack to stack them horizontally
 
result_hstack = np.hstack((arr1, arr2))

print(result_hstack)


# 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
Ans:
fliplr() Function
Purpose: fliplr() flips or reverses the order of elements in a 2D array along the left-right direction (i.e., along the columns). It only works on 2D arrays and higher dimensions where the last dimension represents columns.

Effect: When you apply fliplr() to a 2D array, it reverses the order of the columns, effectively mirroring the array horizontally.

Dimensionality: fliplr() does not change the shape or size of the array; it simply reverses the order of the columns within each row.

Example:
import numpy as np

 Creating a 2D array
arr = np.array([[1, 2, 3],

                [4, 5, 6],
                
                [7, 8, 9]])

Using fliplr to flip the array left-right

result_fliplr = np.fliplr(arr)

print(result_fliplr)

flipud() Function:

Purpose: flipud() flips or reverses the order of elements in a 2D array along the up-down direction (i.e., along the rows). It works on both 1D and higher-dimensional arrays, but its effect is most noticeable in 2D arrays.

Effect: When you apply flipud() to a 2D array, it reverses the order of the rows, effectively mirroring the array vertically.

Dimensionality: flipud() also does not change the shape or size of the array; it simply reverses the order of the rows.

EXample:
import numpy as np

Creating a 2D array

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

Using flipud to flip the array up-down

result_flipud = np.flipud(arr)

print(result_flipud)




# 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
Ans:
The array_split() method in NumPy is used to split an array into multiple sub-arrays. Unlike the split() method, which requires the array to be split into equally sized sub-arrays, array_split() can handle uneven splits, making it more flexible when dealing with arrays that don't divide evenly.

Functionality of array_split()
Purpose: array_split() divides an array into a specified number of sub-arrays. It can be used with both 1D and multi-dimensional arrays.

numpy.array_split(ary, indices_or_sections, axis=0)

ary: The input array to be split.
indices_or_sections: This can be an integer indicating the number of sub-arrays to create or a list of indices at which to split the array.
axis: The axis along which to split the array (default is axis 0).

Handling Uneven Splits:

When the array cannot be evenly divided into the desired number of sub-arrays, array_split() distributes the elements as evenly as possible. The function creates sub-arrays such that some sub-arrays may have one more element than others. The first few sub-arrays in the output will have more elements if the division is uneven.

Example:
import numpy as np

 Creating a 1D array
 
arr = np.array([1, 2, 3, 4, 5, 6, 7])

#Splitting the array into 3 sub-arrays

result = np.array_split(arr, 3)

print(result)



# 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
Ans:
Vectorization in NumPy
Vectorization refers to the process of applying operations to entire arrays (or vectors) in one go, rather than iterating over elements individually in loops. This allows NumPy to leverage low-level optimizations, often using compiled C code, which can execute operations much faster than native Python loops.

Key Benefits of Vectorization:
Performance: Vectorized operations are significantly faster than equivalent operations written with Python loops because they reduce the overhead of Python's dynamic typing and make better use of CPU caches and SIMD (Single Instruction, Multiple Data) instructions.
Code Simplicity: Vectorized code is often more concise and easier to read, as it eliminates the need for explicit loops.

Example:

import numpy as np

 Creating two arrays
 
a = np.array([1, 2, 3, 4])

b = np.array([10, 20, 30, 40])

 Vectorized addition
 
result = a + b

print(result)

Broadcasting in NumPy:

Broadcasting is a mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes. When performing operations between arrays of different shapes, NumPy automatically "broadcasts" the smaller array over the larger array so that their shapes are compatible.

Broadcasting Rules:
Alignment from the Right: NumPy compares the shapes of the arrays element-wise, starting from the rightmost dimension.
Compatibility:
If the dimensions are equal, they are compatible.
If one dimension is 1, it can be broadcast to match the other dimension.
If neither dimension is 1, and they are not equal, broadcasting is not possible.
Example:

import numpy as np

 Creating an array
 
a = np.array([1, 2, 3])

Broadcasting a scalar value

result = a * 2

print(result)



In [3]:
import numpy as np



In [11]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np


array = np.random.randint(1, 101, size=(3, 3))

print("Original array:")
print(array)


transposed_array = array.T

print("\nTransposed array:")
print(transposed_array)


Original array:
[[23 46 30]
 [84 17 38]
 [60 10 25]]

Transposed array:
[[23 84 60]
 [46 17 10]
 [30 38 25]]


In [12]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
import numpy as np


array_1d = np.arange(10)

print("Original 1D array:")
print(array_1d)


array_2x5 = array_1d.reshape(2, 5)

print("\nReshaped to 2x5 array:")
print(array_2x5)


array_5x2 = array_2x5.reshape(5, 2)

print("\nReshaped to 5x2 array:")
print(array_5x2)


Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
import numpy as np


array_4x4 = np.random.rand(4, 4)

print("Original 4x4 array:")
print(array_4x4)


array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("\n6x6 array with border of zeros:")
print(array_6x6)


Original 4x4 array:
[[0.73487538 0.37085555 0.02859286 0.36490311]
 [0.67021781 0.47344023 0.48014831 0.02499538]
 [0.97210786 0.79002748 0.03150862 0.61028568]
 [0.31193031 0.404333   0.95683279 0.63228419]]

6x6 array with border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.73487538 0.37085555 0.02859286 0.36490311 0.        ]
 [0.         0.67021781 0.47344023 0.48014831 0.02499538 0.        ]
 [0.         0.97210786 0.79002748 0.03150862 0.61028568 0.        ]
 [0.         0.31193031 0.404333   0.95683279 0.63228419 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [14]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np


array = np.arange(10, 65, 5)  

print("Array of integers from 10 to 60 with a step of 5:")
print(array)


Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


In [15]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
#(uppercase, lowercase, title case, etc.) to each element
import numpy as np


string_array = np.array(['python', 'numpy', 'pandas'])


uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(string_array)
titlecase_array = np.char.title(string_array)
capitalize_array = np.char.capitalize(string_array)

print("Original array:")
print(string_array)

print("\nUppercase transformation:")
print(uppercase_array)

print("\nLowercase transformation:")
print(lowercase_array)

print("\nTitle case transformation:")
print(titlecase_array)

print("\nCapitalize transformation:")
print(capitalize_array)


Original array:
['python' 'numpy' 'pandas']

Uppercase transformation:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase transformation:
['python' 'numpy' 'pandas']

Title case transformation:
['Python' 'Numpy' 'Pandas']

Capitalize transformation:
['Python' 'Numpy' 'Pandas']


In [16]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array


words_array = np.array(['hello', 'world', 'numpy'])


def insert_spaces(word):
    return ' '.join(word)


vectorized_insert_spaces = np.vectorize(insert_spaces)
spaced_words_array = vectorized_insert_spaces(words_array)

print("Original array of words:")
print(words_array)

print("\nArray with spaces inserted between each character:")
print(spaced_words_array)


Original array of words:
['hello' 'world' 'numpy']

Array with spaces inserted between each character:
['h e l l o' 'w o r l d' 'n u m p y']


In [17]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division
import numpy as np

# Step 1: Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

# Step 2: Perform element-wise addition
addition_result = array1 + array2
print("\nElement-wise addition:")
print(addition_result)

# Perform element-wise subtraction
subtraction_result = array1 - array2
print("\nElement-wise subtraction:")
print(subtraction_result)

# Perform element-wise multiplication
multiplication_result = array1 * array2
print("\nElement-wise multiplication:")
print(multiplication_result)

# Perform element-wise division
division_result = array1 / array2
print("\nElement-wise division:")
print(division_result)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [18]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements
import numpy as np


identity_matrix = np.eye(5)

print("5x5 Identity Matrix:")
print(identity_matrix)


diagonal_elements = np.diag(identity_matrix)

print("\nDiagonal elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal elements:
[1. 1. 1. 1. 1.]


In [19]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
#this array.


# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)

print("Random Array:")
print(random_array)

# Step 2: Define a function to check if a number is prime
def is_prime(num):
    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6
    return True

# Step 3: Use the function to find all prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]

print("\nPrime numbers in the array:")
print(prime_numbers)


Random Array:
[597  51  65 602 831 329 342 817 257 624 559 767  51 999 836 228 582  13
 970 833 832 444 980 147 513 793 205 335 875  26 902 660 967 772 639  97
 679 400 189 162 878 234 545 226 889 765  14 772 614 763 273  71 916 655
  58 900 946 550 202 803 482 719 448 626 867 533 205 181 790 608 655 945
 591 316 662 950 156 860 349 798 515 999 981 450 492 196 301 760 464 417
 984 336 858 672 949 694 363 205 695 329]

Prime numbers in the array:
[257, 13, 967, 97, 71, 719, 181, 349]


In [22]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
# averages

import numpy as np

# Step 1: Create a NumPy array representing daily temperatures for a month (30 days)
# For simplicity, generating random temperatures between 0 and 35 degrees Celsius
daily_temperatures = np.random.uniform(0, 35, size=28)

print("Daily temperatures for the month:")
print(daily_temperatures)

# Step 2: Reshape the array to group temperatures by week (7 days per week)
# Reshaping to a (4, 7) array, assuming 4 weeks in the month
weekly_temperatures = daily_temperatures.reshape(4, 7)

print("\nTemperatures reshaped into weeks:")
print(weekly_temperatures)

# Step 3: Calculate the average temperature for each week
weekly_averages = np.mean(weekly_temperatures, axis=1)

print("\nWeekly averages:")
print(weekly_averages)

    
    

Daily temperatures for the month:
[ 3.21673556  6.75516759 17.06080488 19.360325   20.39998182 16.32769431
  8.44769204 31.99664417  0.36553289  6.83431952  7.57948859  5.14377009
 10.74612719 13.29471606 19.78495689 19.25591348 11.75876896 27.4884673
 13.40945098 20.46177383 12.25727724  1.67431972 31.61288467 33.24118805
 17.96025762  6.45708039  9.30770311 24.91943109]

Temperatures reshaped into weeks:
[[ 3.21673556  6.75516759 17.06080488 19.360325   20.39998182 16.32769431
   8.44769204]
 [31.99664417  0.36553289  6.83431952  7.57948859  5.14377009 10.74612719
  13.29471606]
 [19.78495689 19.25591348 11.75876896 27.4884673  13.40945098 20.46177383
  12.25727724]
 [ 1.67431972 31.61288467 33.24118805 17.96025762  6.45708039  9.30770311
  24.91943109]]

Weekly averages:
[13.08120017 10.85151407 17.77380124 17.88183781]
